/**
 * Created by ztadmin on 2018/1/16.
 */
export const TEST = 'TEST';
export const REQUEST_API = "REQUEST_API"

export const REQUEST_API_NEW_APP = "REQUEST_API_NEW_APP"
export const REQUEST_API_NEW_GAME = "REQUEST_API_NEW_GAME"
export const REQUEST_API_TOP_FREE = "REQUEST_API_TOP_FREE"
export const REQUEST_API_TOP_SELL = "REQUEST_API_TOP_SELL"
export const REQUEST_API_TOP_PAID = "REQUEST_API_TOP_PAID"
